const cst = {
  ACTION_OPEN_TAB: 'open.tab',
  ACTION_LOADING: 'loading',
  ACTION_LOADED: 'loaded',
  ACTION_LOGIN: 'login',
  ACTION_REGISTER: 'register',
  ACTION_FETCHED_FAIL: 'ACTION-FETCH-FAIL',
  ACTION_LOGOUT: 'logout',
  ACTION_GET_MOVIE_INFO: 'GET-MOVIE-INFO',
  ACTION_SWITCH_PAGE: 'SWITCH-PAGE',
  PAGE_HOME: 'PAGE-MAIN',
  PAGE_SEARCH: 'PAGE-SEARCH',
};

export default cst;
